server:
  port: 8881
  servlet:
    context-path: /auth
spring:
  redis:
    host: 127.0.0.1
    port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/webwork?useSSL=false
    username: root
    password: 12345